### ISSUE TITLE
預設鍵盤檔 trime 3.2.14 只剩注音

### ISSUE THREAD

**Issue by DCGoner** [oniondelta/Onion_Trime_Files#1]
APP 更新到 v3.2.18 後，
預設的鍵盤檔布局只剩下注音
像這樣：https://i.imgur.com/UvqfZhL.jpeg
使用的方案是：洋蔥手機方案_20240501 洋蔥同文注音plus版
系統是小米14、Android 14
降回 3.2.17 就恢復正常。
另，3.2.17 雖然布局顯示正常，但每次切成英文模式，
要再打字時，又會回到中文模式
像這樣：https://i.imgur.com/kO5Q1Or.jpeg
左上角會顯示【英】，但會回到中文模式
不曉得是不是 BUG，還是有什麼設定改善？

3.2.17 的版本：https://github.com/osfans/trime/releases/tag/v3.2.17
3.2.18 的版本：https://github.com/osfans/trime/releases/tag/v3.2.18

**Comment by oniondelta** [comment]
目前測試和使用的 [版本](https://github.com/oniondelta/Onion_Trime_Files?tab=readme-ov-file#%E7%89%88%E6%9C%AC) 為  trime 3.2.14 版，
經驗是鍵盤檔( .trime.yaml )無法完全符合每一版 trime app！
基本需特規，可看下載 zip 中的資料夾，
這邊已提供了 3 個版本的 trime 鍵盤檔( .trime.yaml )！

trime app 版本之更新，
常發生某程式碼之前支援可行，後面無法支援（ 不是不支援）的情形，因而產生錯誤！
之前有一版不吃「引用」格式，
結果這邊鍵盤檔( .trime.yaml )全部直接不能用，

看第一張圖，發現有些鍵盤小字符沒顯示，但第二張圖卻有顯示，有發生錯亂情形。
第二張圖，英文狀態下，鍵盤上不應該顯示ㄅㄆㄇㄈ，應該顯示 abcd，也是發生錯亂的表示。

目前如要正常使用，建議 trime app 退到當初針對性修改的 3.2.14 版，
那邊有 bug 才好討論，看看可否修改設定檔去避免 bug。

之後可能傾向直攻 Nightly Build 3.2.19 版或之後較多按讚的版本！
較多按讚的版本基本較穩定，修改設定檔才較有意義。
3.2.17 和 3.2.18 目前感覺不是很穩定！

**Comment by DCGoner** [comment]
後來有退回方案內附的 3.2.14 版，字符顯示正常，但中英模式切換還是有問題。
目前是退回方案內付的 3.2.8 版，字符顯示正常，中英模式切換也能正常記憶，
而且 3.2.8 版的 APP 設定可查看剪貼板和草稿箱的內容，之後的版本好像都不行，
只能設定記錄的數量，現在先用 3.2.8 版就好。感謝作者回覆

**Comment by oniondelta** [comment]
這邊 trime app 為「3.2.14」版，但 android 版本和你不同，
用鍵盤設定檔「洋蔥注音3214k_M.trime.yaml」沒遇中英模式切換問題😱

相關聯，猜測為「洋蔥注音3214k_M.trime.yaml」鍵盤設定檔以下：

`reset_ascii_mode: true` ：切换键盘、重新弹出键盘时，是否重置到当前 keyboard 指定的 ascii_mode 描述的状态（默认 false）。与style/reset_ascii_mode(指定弹出键盘时是否重置 ASCII 状态）配合使用。

好似當初加入該條是因「符號鍵盤」等非主鍵盤中的符號必須強制限定為英文狀態，不然點擊會出全形等中文標點，
但跳回主鍵盤（注音）時，又會呈現英文狀態，故增加該條，
先前版本沒以上問題，「3.2.14」版無法自動跳回，故增加條目，

`lock: true` 在不同程序中切換時鎖住當前鍵盤，不返回默認的主鍵盤。用於單手鍵盤等。（true：鎖住；false：不鎖，可省略不寫）

可能：`reset_ascii_mode: true` 和 `ascii_mode: 0` 設定衝突，切換到「英文模式」，因為這兩條目，又被強制切回來中文！

環環相扣，改掉 `reset_ascii_mode: true`，那從「符號鍵盤」等需轉換為英文模式的鍵盤切回主鍵盤（注音），是否能跳回中文模式？！

以下有其他網友反應類似問題：
https://github.com/osfans/trime/issues/1092

**Comment by DCGoner** [comment]
剛剛測試了方案內附的 3.2.14 版，並把該條參數修改成 false，
中英模式切換能正常記憶了！感謝提供解決辦法😊

**Comment by oniondelta** [comment]
等 trime app 那端穩定吧！
早期 3.2.1 版絲滑多了！
現在加了一堆功能，有些功能是不錯，如「剪貼簿」
但之後的版本，這邊都有很卡頓！且 bug 多。
且有些 bug，在不同版的 android，有人有，有人沒有
這邊寫鍵盤設定檔，一時也不知道怎麼改！

**Comment by oniondelta** [comment]
望 trime app 那端穩定！
早期 3.2.1 版和之前的版本絲滑多了！

**Comment by oniondelta** [comment]
> 剛剛測試了方案內附的 3.2.14 版，並把該條參數修改成 false， 中英模式切換能正常記憶了！感謝提供解決辦法😊

剛剛試了一些組合，發現都會有 bug 產生：


1. 以下設定切換到「數字鍵盤」，再切回「主鍵盤（注音）」，會到英文模式

```yaml
style:
  reset_ascii_mode: true
preset_keyboards:
  bpmfmobileplus:
     reset_ascii_mode: false
```

2. 以下設定從「主鍵盤（注音）」切換到「符號鍵盤」或「顏文字鍵盤」，會還在中文狀態，無法直接輸入

```yaml
style:
  reset_ascii_mode: false
preset_keyboards:
  bpmfmobileplus:
     reset_ascii_mode: true
```

3. 以下設定這邊全部情形OK，你那邊英文模式下無法切換到英文鍵盤，還是打出中文😱

```yaml
style:
  reset_ascii_mode: true
preset_keyboards:
  bpmfmobileplus:
     reset_ascii_mode: true
```

**Comment by DCGoner** [comment]
剛剛再次看了「洋蔥注音3214k_M.trime.yaml」，
才發現 reset_ascii_mode 這條參數出現了 78次！！
修改時只動了這行【reset_ascii_mode: true #顯示鍵盤時重置為中文狀態】，改成 false
其它的都沒動到。在這條件下，測試了：

主鍵盤（注音）中文模式，點選左下角*，選符集，選右上角123，
進入數字鍵盤（這時可正常輸入 0～9 和旁邊的 #/*=-+%，都是半形），
再選返回，可正常回到中文模式。
主鍵盤（注音）英文模式進入數字鍵盤，能正常輸入，也能正常返回英文模式。

主鍵盤（注音）中文模式，點選左下角*，選左上角顏文字^_^，
如果顏文字是常用的符號為首，例如：^_^，則無法順利輸入，會出現【^】的相關符號
如果顏文字是不常用的符號為首，例如：٩，則能正常輸入，像這幾個：
【↖(^ω^)↗  ٩(๑^o^๑)۶  ヾ ^_^♪】都沒問題。
主鍵盤（注音）英文模式進入顏文字鍵盤，全部都能輸入。

至於符號鍵盤，不太確定是指哪個頁面（是指點選左下角*，進入的初始頁面【#!?】嗎？），
就沒有測試了。以上，感覺除了顏文字有一點問題，其它狀況都很正常。

**Comment by oniondelta** [comment]
- 以下為全局：
```yaml
style:
  reset_ascii_mode: true #顯示鍵盤時重置為中文狀態」為全局
```
- 以下為針對個別鍵盤：
```yaml
preset_keyboards:
  個別鍵盤:
     reset_ascii_mode: true
```

- 「＊」向上滑就有「數字鍵盤」（之前版本絲滑，這樣調出更快速）

- 「顏文字」出問題，非主鍵盤之「符號」也會出問題。

- 「符號鍵盤」就是點選「＊」中的【#!?】，第一頁中文符號不會有問題，第二頁英文符號會有問題！

- 前面舉例錯誤：「數字鍵盤」的符號輸出是特例用：用「preset_keys:」建構按鍵使用「cmmit:」，「符號鍵盤」「顏文字鍵盤」的輸出用：「click:」。「數字鍵盤」的「cmmit:」不被中英模式切換影響。

- 以上看似有解法，再修改研究看看！有無其他 bug！

**Comment by oniondelta** [comment]
- 發現對稱符號「[]」「{}」等用「commit:」如此修改，游標無法置中

- 每個「顏文字」按鍵和「半形符號」按鍵都建立一個「preset_keys:」用「commit:」輸出的 key，有點太多太雜了！

- 每個「顏文字」和「半形符號」按鍵用精簡寫法，操作沒問題，但會出現以下顯示 bug：

![Screenshot_20240505-120649](https://github.com/oniondelta/Onion_Trime_Files/assets/54584047/45d6b197-e8c9-4201-a35f-235b724dfd85)


### 目前結論

如遇英文模式輸出中文的問題，改以下可解決，但會有 bug，現階段不好「修改設定檔」，去避免所有 bug。

```yaml
style:
  reset_ascii_mode: false #顯示鍵盤時重置為中文狀態」為全局
```

目前測試研判 trime app 端對以下程式碼失效，導致 bug？：
```yaml
preset_keyboards:
  個別鍵盤:
     reset_ascii_mode: true
```

相關反應：https://github.com/osfans/trime/issues/1272
